[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/vendor/three.min.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
